name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24

    - name: Unit tests
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        POSTGRES_DB: test
        POSTGRES_USER: test
        POSTGRES_PASSWORD: test
      run: "go test -coverprofile=cover.out ./..."

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: cover.out

    - name: Modver
      if: ${{ github.event_name == 'pull_request' }}
      uses: bobg/modver@v2.11.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pull_request_url: https://github.com/${{ github.repository }}/pull/${{ github.event.number }}
